# Generated by Django 3.2 on 2022-09-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='locations_id',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='announcement_id',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='announcement_id',
            new_name='announcement',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='preferences',
            old_name='locations_id',
            new_name='locations',
        ),
    ]
