# Generated by Django 3.2 on 2022-10-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0003_auto_20221001_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
