# Generated by Django 3.2 on 2022-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0004_alter_photos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
