# Generated by Django 3.2 on 2022-10-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0007_auto_20221013_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
