# Generated by Django 3.2 on 2022-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0008_alter_locations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
