# Generated by Django 3.2 on 2022-10-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulettin_board_app', '0009_alter_locations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
