# Generated by Django 3.2 on 2022-10-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_alter_footballclubs_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FootballClubs',
        ),
    ]
